### ISSUE TITLE
History Ref type mismatches with assigned value (when using mixin with non integer id field)

### ISSUE THREAD

**Issue by joemocquant** [flume/enthistory#62] opened 2024-12-24 06:25 UTC
**Describe the bug**

When using a mixin containing the `id` field that is not of integer type, the generated code does not compile. The Ref type is of type Int and mismatches with the type of the value being assigned to it.

**To Reproduce**

Create a simple entity with a mixin containing the `id` field:

```
type User struct {
	ent.Schema
}

type IDMixin struct {
	mixin.Schema
}

func (IDMixin) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Default(uuid.New),
	}
}

func (User) Mixin() []ent.Mixin {
	return []ent.Mixin{
		IDMixin{},
	}
}

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			Default("unknown"),
	}
}
```

Here is the entc relevant code:
```
func main() {
	if err := enthistory.Generate("./schema", []ent.Interface{
		// Add all the schemas you want history tracking on here
		schema.User{},
	},
		enthistory.WithInheritIdType(),
		enthistory.WithUpdatedBy("userId", enthistory.ValueTypeUUID),
		enthistory.WithHistoryTimeIndex(),
		enthistory.WithImmutableFields(),
		// Without this line, all triggers will be used as the default
		enthistory.WithTriggers(enthistory.OpTypeInsert),
	); err != nil {
		log.Fatal(fmt.Sprintf("running enthistory codegen: %v", err))
	}

	if err := entc.Generate("./schema", &gen.Config{
		IDType: &field.TypeInfo{Type: field.TypeString},
		Features: []gen.Feature{
			gen.FeatureSnapshot,
		},
	},
		entc.Extensions(
			enthistory.NewHistoryExtension(enthistory.WithAuditing()),
		),
	); err != nil {
		log.Fatal("running ent codegen:", err)
	}
}
```

**Expected behavior**

The code generated should compile. 

From what I understand, the Ref type should match the id type of the original table (here: UUID) if using `enthistory.WithInheritIdType()`. If not using `enthistory.WithInheritIdType()`, the assigned value should be of type Int.

**Screenshots**

For example, in `history_from_mutation.go`, there are compilation errors: 
> cannot use id (variable of type uuid.UUID) as int value in argument to create.SetOperation(EntOpToHistoryOp(m.Op())).SetHistoryTime(time.Now()).SetRef

**Additional context**

There were a related issue in the past: https://github.com/flume/enthistory/pull/31.

Thanks for the great work on this package!

**Comment by frisbm** [comment] 2024-12-24 17:34
@joemocquant Thanks for informing us about this bug, I was able to reproduce it locally and just got a fix PR up for it. We should be able to get this merged in a couple days after the holiday break, but if you're looking to use it sooner you could use the PR's branch in your go.mod in the meantime.

**Closed** 2024-12-26 21:33 UTC
Labels: bug

**Comment by frisbm** [comment] 2024-12-26 21:35
@joemocquant version `v0.15.5` contains the fix, thanks again for bringing this issue up

**Comment by joemocquant** [comment] 2024-12-26 21:35
Thanks for quick investigation and fix!

As a follow-up, when also using entgql like in this basic example:

```
func main() {
	if err := enthistory.Generate("./schema", []ent.Interface{
		// Add all the schemas you want history tracking on here
		schema.User{},
	},
		enthistory.WithUpdatedBy("userId", enthistory.ValueTypeUUID),
		enthistory.WithHistoryTimeIndex(),
		enthistory.WithImmutableFields(),
	); err != nil {
		log.Fatal(fmt.Sprintf("running enthistory codegen: %v", err))
	}

	ex, err := entgql.NewExtension(
		entgql.WithWhereInputs(true),
	)
	if err != nil {
		log.Fatalf("creating entgql extension: %v", err)
	}

	if err := entc.Generate("./schema", &gen.Config{
		Features: []gen.Feature{},
	},
		entc.Extensions(
			enthistory.NewHistoryExtension(enthistory.WithAuditing()),
		),
		entc.Extensions(ex),
	); err != nil {
		log.Fatal("running ent codegen:", err)
	}
}
```

It results in this error:

> running ent codegen:execute template "client": template: node.tmpl:317:16: executing "client/fields/additional" at <gqlIDType (filterNodes $.Nodes (skipMode "type")) $.IDType>: error calling gqlIDType: entgql: mixed id types must be type string or implement the graphql.Marshaller/graphql.Unmarshaller interfaces
exit status 1
generate.go:3: running "go": exit status 1

This error disapppears if using `enthistory.WithInheritIdType()`.

It looks like when using entgql, the ids across tables need to be of the same type, and the error happens because the history tables use Integer as a the `id` type, and the other tables using UUID (via the mixin). Using `WithInheritIdType` ensures to have the same original id type for the history tables.

Any solution on how to keep uuid for root tables, and id for history tables?
- Event ordering would be lost if not having integer id for history tables
- Not looking to convert the id type into string as it would be less performant at the db level if it represents a uuid.

**Comment by frisbm** [comment] 2024-12-26 21:54
@joemocquant So, I'm not super familiar with entql since we don't use it with enthistory internally. But from what I've seen, ID types need to be consistent across all schemas, which is why you'd need `enthistory.WithInheritIdType()`. enthistory doesn't really have a say in how entql generates code related to IDs because history schemas are generated first.

Just wanted to point out that enthistory keeps event ordering intact using the `history_time` fields in the history schemas if using UUID's with history schemas is a concern

Some example generated snippets:

```go
func (tsh *TestSkipHistory) Next(ctx context.Context) (*TestSkipHistory, error) {
	client := NewTestSkipHistoryClient(tsh.config)
	return client.Query().
		Where(
			testskiphistory.Ref(tsh.Ref),
			testskiphistory.HistoryTimeGT(tsh.HistoryTime),
		).
		Order(testskiphistory.ByHistoryTime()).
		First(ctx)
}

func (tsh *TestSkipHistory) Prev(ctx context.Context) (*TestSkipHistory, error) {
	client := NewTestSkipHistoryClient(tsh.config)
	return client.Query().
		Where(
			testskiphistory.Ref(tsh.Ref),
			testskiphistory.HistoryTimeLT(tsh.HistoryTime),
		).
		Order(testskiphistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}

func (tshq *TestSkipHistoryQuery) Earliest(ctx context.Context) (*TestSkipHistory, error) {
	return tshq.
		Order(testskiphistory.ByHistoryTime()).
		First(ctx)
}

func (tshq *TestSkipHistoryQuery) Latest(ctx context.Context) (*TestSkipHistory, error) {
	return tshq.
		Order(testskiphistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}
```
